const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
const SEND_REGISTER_FORM = 'SEND_REGISTER_FORM';
const SUCCES_REGISTER = 'SUCCES_REGISTER';
const ERROR_REGISTER = 'ERROR_REGISTER';

export default {
  UPDATE_REGISTER_FORM,
  SEND_REGISTER_FORM,
  SUCCES_REGISTER,
  ERROR_REGISTER
};
